FROM golang:1.16-stretch

SHELL ["/bin/bash", "-c"]
RUN apt update && apt-get install -y vim git

# golang
WORKDIR /タイトル
ENV GO111MODULE on
RUN go get -u github.com/golang/protobuf/protoc-gen-go \
  && go get -u github.com/pilu/fresh
RUN git config --global user.email "keigo2356@gmail.com" \
  && git config --global user.name "keigooba"

EXPOSE 8080

CMD ["fresh"]
