FROM golang:1.16-alpine as builder
WORKDIR /go/src
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -v -o popular

FROM gcr.io/cloud-builders/gcloud:latest
WORKDIR /go/src
COPY . .

COPY --from=builder /go/src/popular /popular

ARG _TWITTER_KEY
ARG _TWITTER_SECRET
ARG _PIXABAY_KEY
ARG _PRIVATE_KEY_ID
ARG _PRIVATE_KEY
ENV TWITTER_KEY ${_TWITTER_KEY}
ENV TWITTER_SECRET ${_TWITTER_SECRET}
ENV PIXABAY_KEY ${_PIXABAY_KEY}
ENV PRIVATE_KEY_ID ${_PRIVATE_KEY_ID}
ENV PRIVATE_KEY ${_PRIVATE_KEY}

ENTRYPOINT ["/popular"]
